### ISSUE TITLE
Bucket/Channel

### ISSUE THREAD

**Issue by evanzummeren** [raditube/tool#33]
# Bucket/Channel
The access url is ```localhost:8080/bucket/{bucket_id}/channel/{channel_id}```

[design](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-%5Bv2%5D-%E2%80%94-Front-end?node-id=659%3A1868)

## Tasks
- [x] Description, subscribers, videos, active since, presence
- [x] Side menu (this should be sticky, if user clicks on the item, scroll should move)
- [x] Can you make the heading of all the following items also sticky? Like this: https://www.w3schools.com/howto/howto_js_sticky_header.asp
- [x] Videos list
- [x] Uploads over time (the data for this is not ready yet, so probably ignore for now)
- [x] Notes (please use the same elements as the one for Saved Videos and Notes)
- [x] Similar Channels
- [x] User engagement
- [x] Fandom

## Feedback
- [x] The sticky header implementation is good, but can you add .5rem/8px margin to the top of the header so the letters don't touch the top of the screen.
- [x] Can you make sure that there is no text visible between the header and the top of the screen [example](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-%5Bv2%5D-%E2%80%94-Front-end?node-id=1475%3A1569)
